name = "web-connect-worker"
main = "backend/worker.js"
compatibility_date = "2024-10-01"

[vars]
# secrets are injected via Cloudflare Dashboard

kv_namespaces = [
  { binding = "USERS_KV", id = "7ce442918f0241198ce458d451ba1d0f" },
  { binding = "SESSIONS_KV", id = "9ed7fc983e2f494e8a4fb158f8790a69" },
  { binding = "MESSAGES_KV", id = "403caaa62b454769b3eb087b643bfc54" }
]
